import '../astro/ephemeris.dart';

/// One of the 27 lunar mansions.
class NakshatraInfo {
  const NakshatraInfo({
    required this.index,
    required this.english,
    required this.hindi,
    required this.lord,
    required this.deityEnglish,
    required this.deityHindi,
    required this.symbolEnglish,
    required this.gana,
    required this.yoni,
    required this.nadi,
  });

  /// Zero-based index from Ashwini.
  final int index;
  final String english;
  final String hindi;

  /// Vimshottari dasha lord.
  final Graha lord;
  final String deityEnglish;
  final String deityHindi;
  final String symbolEnglish;
  final Gana gana;
  final String yoni;
  final Nadi nadi;
}

enum Gana { deva, manushya, rakshasa }

enum Nadi { adi, madhya, antya }

const double nakshatraSpan = 360.0 / 27.0;

const List<NakshatraInfo> nakshatraTable = <NakshatraInfo>[
  NakshatraInfo(
    index: 0,
    english: 'Ashwini',
    hindi: 'अश्विनी',
    lord: Graha.ketu,
    deityEnglish: 'Ashwini Kumaras',
    deityHindi: 'अश्विनी कुमार',
    symbolEnglish: "Horse's head",
    gana: Gana.deva,
    yoni: 'horse',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 1,
    english: 'Bharani',
    hindi: 'भरणी',
    lord: Graha.venus,
    deityEnglish: 'Yama',
    deityHindi: 'यम',
    symbolEnglish: 'Yoni',
    gana: Gana.manushya,
    yoni: 'elephant',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 2,
    english: 'Krittika',
    hindi: 'कृत्तिका',
    lord: Graha.sun,
    deityEnglish: 'Agni',
    deityHindi: 'अग्नि',
    symbolEnglish: 'Razor, flame',
    gana: Gana.rakshasa,
    yoni: 'sheep',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 3,
    english: 'Rohini',
    hindi: 'रोहिणी',
    lord: Graha.moon,
    deityEnglish: 'Brahma',
    deityHindi: 'ब्रह्मा',
    symbolEnglish: 'Cart',
    gana: Gana.manushya,
    yoni: 'serpent',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 4,
    english: 'Mrigashira',
    hindi: 'मृगशिरा',
    lord: Graha.mars,
    deityEnglish: 'Soma',
    deityHindi: 'सोम',
    symbolEnglish: "Deer's head",
    gana: Gana.deva,
    yoni: 'serpent',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 5,
    english: 'Ardra',
    hindi: 'आर्द्रा',
    lord: Graha.rahu,
    deityEnglish: 'Rudra',
    deityHindi: 'रुद्र',
    symbolEnglish: 'Teardrop',
    gana: Gana.manushya,
    yoni: 'dog',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 6,
    english: 'Punarvasu',
    hindi: 'पुनर्वसु',
    lord: Graha.jupiter,
    deityEnglish: 'Aditi',
    deityHindi: 'अदिति',
    symbolEnglish: 'Quiver of arrows',
    gana: Gana.deva,
    yoni: 'cat',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 7,
    english: 'Pushya',
    hindi: 'पुष्य',
    lord: Graha.saturn,
    deityEnglish: 'Brihaspati',
    deityHindi: 'बृहस्पति',
    symbolEnglish: "Cow's udder",
    gana: Gana.deva,
    yoni: 'sheep',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 8,
    english: 'Ashlesha',
    hindi: 'आश्लेषा',
    lord: Graha.mercury,
    deityEnglish: 'Nagas',
    deityHindi: 'नाग',
    symbolEnglish: 'Coiled serpent',
    gana: Gana.rakshasa,
    yoni: 'cat',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 9,
    english: 'Magha',
    hindi: 'मघा',
    lord: Graha.ketu,
    deityEnglish: 'Pitris',
    deityHindi: 'पितृगण',
    symbolEnglish: 'Royal throne',
    gana: Gana.rakshasa,
    yoni: 'rat',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 10,
    english: 'Purva Phalguni',
    hindi: 'पूर्वा फाल्गुनी',
    lord: Graha.venus,
    deityEnglish: 'Bhaga',
    deityHindi: 'भग',
    symbolEnglish: 'Front of a bed',
    gana: Gana.manushya,
    yoni: 'rat',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 11,
    english: 'Uttara Phalguni',
    hindi: 'उत्तरा फाल्गुनी',
    lord: Graha.sun,
    deityEnglish: 'Aryaman',
    deityHindi: 'अर्यमा',
    symbolEnglish: 'Back of a bed',
    gana: Gana.manushya,
    yoni: 'cow',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 12,
    english: 'Hasta',
    hindi: 'हस्त',
    lord: Graha.moon,
    deityEnglish: 'Savitr',
    deityHindi: 'सविता',
    symbolEnglish: 'Open hand',
    gana: Gana.deva,
    yoni: 'buffalo',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 13,
    english: 'Chitra',
    hindi: 'चित्रा',
    lord: Graha.mars,
    deityEnglish: 'Tvashtar',
    deityHindi: 'त्वष्टा',
    symbolEnglish: 'Bright jewel',
    gana: Gana.rakshasa,
    yoni: 'tiger',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 14,
    english: 'Swati',
    hindi: 'स्वाती',
    lord: Graha.rahu,
    deityEnglish: 'Vayu',
    deityHindi: 'वायु',
    symbolEnglish: 'Young shoot in the wind',
    gana: Gana.deva,
    yoni: 'buffalo',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 15,
    english: 'Vishakha',
    hindi: 'विशाखा',
    lord: Graha.jupiter,
    deityEnglish: 'Indra and Agni',
    deityHindi: 'इन्द्राग्नि',
    symbolEnglish: 'Triumphal arch',
    gana: Gana.rakshasa,
    yoni: 'tiger',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 16,
    english: 'Anuradha',
    hindi: 'अनुराधा',
    lord: Graha.saturn,
    deityEnglish: 'Mitra',
    deityHindi: 'मित्र',
    symbolEnglish: 'Lotus',
    gana: Gana.deva,
    yoni: 'deer',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 17,
    english: 'Jyeshtha',
    hindi: 'ज्येष्ठा',
    lord: Graha.mercury,
    deityEnglish: 'Indra',
    deityHindi: 'इन्द्र',
    symbolEnglish: 'Earring, umbrella',
    gana: Gana.rakshasa,
    yoni: 'deer',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 18,
    english: 'Mula',
    hindi: 'मूल',
    lord: Graha.ketu,
    deityEnglish: 'Nirriti',
    deityHindi: 'निर्ऋति',
    symbolEnglish: 'Bunch of roots',
    gana: Gana.rakshasa,
    yoni: 'dog',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 19,
    english: 'Purva Ashadha',
    hindi: 'पूर्वाषाढ़ा',
    lord: Graha.venus,
    deityEnglish: 'Apah',
    deityHindi: 'आपः',
    symbolEnglish: 'Winnowing basket',
    gana: Gana.manushya,
    yoni: 'monkey',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 20,
    english: 'Uttara Ashadha',
    hindi: 'उत्तराषाढ़ा',
    lord: Graha.sun,
    deityEnglish: 'Vishvedevas',
    deityHindi: 'विश्वेदेव',
    symbolEnglish: "Elephant's tusk",
    gana: Gana.manushya,
    yoni: 'mongoose',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 21,
    english: 'Shravana',
    hindi: 'श्रवण',
    lord: Graha.moon,
    deityEnglish: 'Vishnu',
    deityHindi: 'विष्णु',
    symbolEnglish: 'Three footprints',
    gana: Gana.deva,
    yoni: 'monkey',
    nadi: Nadi.antya,
  ),
  NakshatraInfo(
    index: 22,
    english: 'Dhanishta',
    hindi: 'धनिष्ठा',
    lord: Graha.mars,
    deityEnglish: 'Eight Vasus',
    deityHindi: 'अष्ट वसु',
    symbolEnglish: 'Drum',
    gana: Gana.rakshasa,
    yoni: 'lion',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 23,
    english: 'Shatabhisha',
    hindi: 'शतभिषा',
    lord: Graha.rahu,
    deityEnglish: 'Varuna',
    deityHindi: 'वरुण',
    symbolEnglish: 'Empty circle',
    gana: Gana.rakshasa,
    yoni: 'horse',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 24,
    english: 'Purva Bhadrapada',
    hindi: 'पूर्व भाद्रपद',
    lord: Graha.jupiter,
    deityEnglish: 'Aja Ekapada',
    deityHindi: 'अज एकपाद',
    symbolEnglish: 'Front of a funeral cot',
    gana: Gana.manushya,
    yoni: 'lion',
    nadi: Nadi.adi,
  ),
  NakshatraInfo(
    index: 25,
    english: 'Uttara Bhadrapada',
    hindi: 'उत्तर भाद्रपद',
    lord: Graha.saturn,
    deityEnglish: 'Ahirbudhnya',
    deityHindi: 'अहिर्बुध्न्य',
    symbolEnglish: 'Back of a funeral cot',
    gana: Gana.manushya,
    yoni: 'cow',
    nadi: Nadi.madhya,
  ),
  NakshatraInfo(
    index: 26,
    english: 'Revati',
    hindi: 'रेवती',
    lord: Graha.mercury,
    deityEnglish: 'Pushan',
    deityHindi: 'पूषा',
    symbolEnglish: 'Fish',
    gana: Gana.deva,
    yoni: 'elephant',
    nadi: Nadi.antya,
  ),
];

/// Nakshatra index 0..26 from a sidereal longitude.
int nakshatraIndexOf(double siderealLongitude) =>
    (siderealLongitude / nakshatraSpan).floor() % 27;

/// Pada 1..4 from a sidereal longitude.
int padaOf(double siderealLongitude) {
  final double within = siderealLongitude % nakshatraSpan;
  return (within / (nakshatraSpan / 4)).floor() + 1;
}

NakshatraInfo nakshatraOf(double siderealLongitude) =>
    nakshatraTable[nakshatraIndexOf(siderealLongitude)];
